### ISSUE TITLE
Do I need lk-neutron.img to make modifications to system? Or, is turning off write protect enough?

### ISSUE THREAD

**Issue by androidars** [neutronscott/flip2#12]
I would like to be able to write, delete, or replace in system and vendor.

If I need lk-neutron.img, where can I find it?

**Comment by neutronscott** [comment]
I believe I erased all the stuff about the lk img once I found the vendor supplied script to allow writes. The lk img was a hex edit hack to ruin the range it applied write protections to during boot up because once it's set it cannot be unset. It's risky to mess with lk partition and the script is enough.
